###############################################################################
#  Copyright 2013 - 2018 Software AG, Darmstadt, Germany and/or its licensors
#
#   SPDX-License-Identifier: Apache-2.0
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.                                                            
#
###############################################################################

version: "3.2"

services:
  base:
    image: ${REG}softwareag_ccbuild/base:${TAG}
    build:
      context: base-os/
      args:
        - BASE_IMAGE=centos:7

  java:
    image: ${REG}softwareag_ccbuild/java:${TAG}
    build:
      context: base-java/
      args:
        - BASE_IMAGE=${REG}softwareag_ccbuild/base:${TAG}
        - NODE_IMAGE=${CC_REG}softwareag/commandcentral-node:${TAG}
    depends_on: 
      - base

  ## This register the repos, the creds, adds the licenses, making a ready to go builder for all the rest
  ## WARNING: Only push to a docker registry if the account used for the repo, the licenses, etc... can be shared accross a team
  ## which is why I don't include the ${REG} prefix on image (but you can add it if that's ok with your use case)
  cc_builder:
    image: softwareag_ccbuild/commandcentral-builder:${TAG}
    ports:
      - 8091 # CCE
      - 8092 # SPM
    build:
      context: ../
      dockerfile: base-infra/base-cc-builder/Dockerfile
      args:
        - BUILDER_IMAGE=${CC_REG}softwareag/commandcentral-builder:${CC_TAG}
        - NODE_IMAGE=${CC_REG}softwareag/commandcentral-node:${TAG}
        - REPO_PRODUCT_URL
        - REPO_FIX_URL
        - REPO_USERNAME                           # Empower or mirror username
        - REPO_PASSWORD                           # Empower or user password
        - LICENSES_URL                            # licenses .zip, e.g. 10.x
