version: "3.0"

services:
  deployer:
    image: ${REGISTRY}softwareag/deployer:10.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PARENT_BUILDER: store/softwareag/commandcentral:10.1.0.8-builder
        PARENT_IMAGE: centos:7
    ports:
      - "5555:5555"
      - "9999:9999"

  deployer_managed:
    image: ${REGISTRY}softwareag/deployer_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: store/softwareag/commandcentral:10.1.0.8-builder
        PARENT_IMAGE: ${REGISTRY}softwareag/deployer:10.1
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1
    depends_on:
      - cc   

  deployer_licensed:
    image: ${REGISTRY}softwareag/deployer_licensed:10.1
    build:
      context: .
      dockerfile: Dockerfile.licensed
      args:
        PARENT_IMAGE: ${REGISTRY}softwareag/deployer:10.1
    ports:
      - "5555:5555"
      - "9999:9999"

  deployer_managed_licensed:
    image: ${REGISTRY}softwareag/deployer_managed_licensed:10.1
    build:
      context: .
      dockerfile: Dockerfile.managed.licensed
      args:
        PARENT_IMAGE: ${REGISTRY}softwareag/deployer_managed:10.1
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1
    depends_on:
      - cc

  cc:
    image: store/softwareag/commandcentral:10.1.0.1-server
    ports:
      - "8090:8090"
      - "8091:8091"
