version: "3"

networks:
  sagdevops:

services:
  dbc:
    image: softwareag/dbc_managed:10.1
    hostname: dbc
    networks:
      - sagdevops
    ports:
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce

  cce:
    image: store/softwareag/commandcentral:10.1.0.1-server
    networks:
      - sagdevops
    ports:
      - "8090:8090"
      - "8091:8091"

  setup:
    image: store/softwareag/commandcentral:10.1.0.1-server
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_SERVER=cce
      - CC_TEMPLATE=dbc
    command: sagccant setup_nostart -Dcc=test -Denv=bpms -Dbuild.dir=/tmp -Dinstall.dir=/opt/softwareag
    depends_on:
      - db
      - cce

  db:
    image: softwareag/oracle-xe-11g
    networks:
      - sagdevops
    ports:
      - "49160:22"
      - "49161:1521"
      - "8080:8080"
    environment: 
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false