version: "3.0"

services:
  msc:
    image: ${REG}softwareag_ccbuild/webmethods-microservicesruntime:${TAG}
    ports:
      - "5555:5555"
      - "9999:9999"

  msc_managed:
    image: ${REG}softwareag_ccbuild/webmethods-microservicesruntime_managed:${TAG}
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1
    links:
      - cc      

  cc:
    image: store/softwareag/commandcentral-server:${TAG}
    ports:
      - "8090:8090"
      - "8091:8091"