version: "3.0"

services:
  msc:
    image: softwareag/msc:10.1
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
    ports:
      - "5555:5555"
      - "9999:9999"

  msc_managed:
    image: softwareag/msc_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1
    links:
      - cc      

  cc:
    image: store/softwareag/commandcentral:10.1.0.1-server
    ports:
      - "8090:8090"
      - "8091:8091"