version: "3"

networks:
  sagdevops:

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: softwareag/oracle-xe-11g
    networks:
      - sagdevops
    ports:
      - "49160:22"
      - "49161:1521"
    environment: 
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false