version: "3.0"

services:
  dbc:
    image: ${REG}softwareag_ccbuild/dbc:${TAG}

  dbc_managed:
    image: ${REG}softwareag_ccbuild/dbc_managed:${TAG}
    ports:
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1
    links:
      - cc      

  cc:
    image: store/softwareag/commandcentral-server:${TAG}
    ports:
      - "8090:8090"
      - "8091:8091"