version: "3.0"

services:

  ## NOTE: Not necessary to push to a docker registry, as this is used as an intermediary image only
  ## which is why I don't include the ${REG} prefix on image (but you can add it if that's ok with your use case)
  dbc_builder:
    image: softwareag_ccbuild/dbc_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        PARENT_IMAGE: softwareag_ccbuild/commandcentral-builder:${TAG}

  dbc_managed:
    image: ${REG}softwareag_ccbuild/dbc_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: softwareag_ccbuild/dbc_builder:${TAG}
        PARENT_IMAGE: ${REG}softwareag_ccbuild/java:${TAG}
    expose:
      - "8092"
      - "8093"
    depends_on:
      - dbc_builder

  dbc:
    image: ${REG}softwareag_ccbuild/dbc:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/dbc_managed:${TAG}
    depends_on:
      - dbc_managed