version: "3"

networks:
  sagdevops:

services:
  cce:
    image: store/softwareag/commandcentral:10.1.0.1-server
    networks:
      - sagdevops
    ports:
      - "8090:8090"
      - "8091:8091"

  setup:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: softwareag/commandcentral:10.1-cli-latest
    environment:
      - REPO_USR
      - REPO_PWD
    volumes:
      - ./:/src
    networks:
      - sagdevops
    command: sagccant setup_norestarts -Dcc=test -Dbuild.dir=/tmp -Dinstall.dir=/opt/softwareag
    depends_on:
      - cce