version: '3.3'

networks:
  sagdevops:

services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
      args:
        baselocaldir: nginx
    restart: always
    networks:
      sagdevops:
        aliases:
          - registry.docker.tests
    ports:
      - "80:80"
      - "443:443"
    links:
      - registryv2
      - registryfrontend
    depends_on:
      - registryv2

  # Actual docker registry
  registryv2:
    image: registry:2
    environment:
      - REGISTRY_HTTP_ADDR=:5000
    restart: always
    networks:
      - sagdevops
    expose:
      - "5000"
    volumes:
      - ${PWD}/registrydata:/var/lib/registry:rw

  # Setup front-end
  registryfrontend:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - sagdevops
    expose:
      - "80"
    links:
      - registryv2
    depends_on:
      - registryv2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry.docker.tests
      - ENV_DOCKER_REGISTRY_PORT=443
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    restart: always