version: '3.3'

networks:
  sagdevops:
    external: true

services:
  # Actual docker registry
  registryv2:
    image: registry:2
    environment:
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.docker.tests.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.docker.tests.key
#      - REGISTRY_AUTH=htpasswd
#      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
#      - REGISTRY_AUTH_HTPASSWD_REALM=registry-realm
    ports:
      - "5000:5000"
    networks:
      - sagdevops
        aliases:
          - registry.docker.tests
    volumes:
      - /mnt/docker_registry/registrydata:/var/lib/registry:rw
      - /mnt/docker_registry/certs:/certs:ro
    restart: always

  # Setup front-end
  registryfrontend:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - sagdevops
    ports:
      - "80:80"
    links:
      - registryv2
    depends_on:
      - registryv2
    environment:
      - ENV_MODE_BROWSE_ONLY=false
      - ENV_DOCKER_REGISTRY_HOST=registry.docker.tests
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    restart: always