version: "3.0"

services:
  abe_builder:
    image: custom/softwareag/abe_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        PARENT_IMAGE: ${REG}softwareag/commandcentral-builder:${TAG}

  abe_managed:
    image: ${REG}softwareag/abe_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: custom/softwareag/abe_builder:${TAG}
        PARENT_IMAGE: ${REG}softwareag/java:${TAG}
    depends_on:
      - abe_builder

  abe:
    image: ${REG}softwareag/abe:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_IMAGE: ${REG}softwareag/abe_managed:${TAG}
    depends_on:
      - abe_managed