ARG PARENT_BUILDER
ARG PARENT_IMAGE

# MUST start with builder image to run provisioning using template.yaml
FROM $PARENT_BUILDER as builder

FROM $PARENT_IMAGE

ARG SAG_CI_HOME

ADD --from=builder /sagdevops-ci-assets $SAG_CI_HOME/