version: '3.3'

networks:
  sagdevops:
    external: true

services:
  nginx:
    image: registry.docker.tests/softwareag/registryproxy:latest
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      sagdevops:
        aliases:
          - registry.docker.tests
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/docker_registry/certs/registry.docker.tests.key:/etc/ssl/private/registry.docker.tests.key
      - /mnt/docker_registry/certs/registry.docker.tests.crt:/etc/ssl/certs/registry.docker.tests.crt
      - /mnt/docker_registry/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /mnt/docker_registry/auth/registry.passwd:/etc/nginx/registry.passwd
    links:
      - registryv2
      - registryweb
    depends_on:
      - registryv2

  # Actual docker registry
  registryv2:
    image: registry:2
    environment:
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: always
    networks:
      - sagdevops
    expose:
      - "5000"
    volumes:
      - /mnt/docker_registry/registrydata:/var/lib/registry:rw

  # Setup front-end
  registryweb:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - sagdevops
    expose:
      - "80"
    links:
      - registryv2
    depends_on:
      - registryv2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry.docker.tests
      - ENV_DOCKER_REGISTRY_PORT=443
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    restart: always