version: "3.0"

services:

  ## NOTE: Not necessary to push to a docker registry, as this is used as an intermediary image only
  ## which is why I don't include the ${REG} prefix on image (but you can add it if that's ok with your use case)
  wmtestsuite_builder:
    image: softwareag_ccbuild/wmtestsuite_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        PARENT_IMAGE: softwareag_ccbuild/commandcentral-builder:${TAG}

  wmtestsuite_managed:
    image: ${REG}softwareag_ccbuild/wmtestsuite_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: softwareag_ccbuild/wmtestsuite_builder:${TAG}
        PARENT_IMAGE: ${REG}softwareag_ccbuild/java:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - wmtestsuite_builder

  wmtestsuite:
    image: ${REG}softwareag_ccbuild/wmtestsuite:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/wmtestsuite_managed:${TAG}
    expose:
      - "5555"
      - "9999"
    depends_on:
      - wmtestsuite_managed

  wmtestsuite_managed_licensed:
    image: ${REG}softwareag_ccbuild/wmtestsuite_managed_licensed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.licensed
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/wmtestsuite_managed:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - wmtestsuite_managed

  wmtestsuite_licensed:
    image: ${REG}softwareag_ccbuild/wmtestsuite_licensed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.licensed
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/wmtestsuite:${TAG}
    expose:
      - "5555"
      - "9999"
    depends_on:
      - wmtestsuite