version: "3.0"

services:

  ## NOTE: Not necessary to push to a docker registry, as this is used as an intermediary image only
  ## which is why I don't include the ${REG} prefix on image (but you can add it if that's ok with your use case)
  umserver_builder:
    image: softwareag_ccbuild/umserver_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        PARENT_IMAGE: softwareag_ccbuild/commandcentral-builder:${TAG}

  umserver_managed:
    image: ${REG}softwareag_ccbuild/umserver_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: softwareag_ccbuild/umserver_builder:${TAG}
        PARENT_IMAGE: ${REG}softwareag_ccbuild/java:${TAG}
    expose:
      - "9000"
      - "8092"
      - "8093"
    depends_on:
      - umserver_builder

  umserver:
    image: ${REG}softwareag_ccbuild/umserver:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/umserver_managed:${TAG}
    expose:
      - "9000"
    depends_on:
      - umserver_managed

  umserver_managed_licensed:
    image: ${REG}softwareag_ccbuild/umserver_managed_licensed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.licensed
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/umserver_managed:${TAG}
    expose:
      - "9000"
      - "8092"
      - "8093"
    depends_on:
      - umserver_managed

  umserver_licensed:
    image: ${REG}softwareag_ccbuild/umserver_licensed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.licensed
      args:
        PARENT_IMAGE: ${REG}softwareag_ccbuild/umserver:${TAG}
    expose:
      - "9000"
    depends_on:
      - umserver