version: '3.3'

networks:
  sagdevops:

volumes:
  gogs-db-data:
  gogs-data:
      
services:
    gogsserver:
      image: registry.docker.tests:5000/softwareag/gogs:latest
      build:
        dockerfile: Dockerfile
        context: .
        args:
          - GOGS_CUSTOM_DIR=/data/gogs/custom
      restart: always
      ports:
       - "10022:22"
       - "10080:3000"
      links:
       - postgres
      environment:
       - RUN_CROND=true
       - GOGS_CUSTOM=/data/gogs/custom
      networks:
       - sagdevops
      volumes:
       - gogs-data:/data
      depends_on:
       - postgres

    postgres:
      image: postgres:9.5
      restart: always
      environment:
       - "POSTGRES_USER=${POSTGRES_USER}"
       - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
       - "POSTGRES_DB=gogs"
      volumes:
       - gogs-db-data:/var/lib/postgresql/data
      networks:
       - sagdevops